test add-back-ubuntu-focal-target

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -65,17 +65,18 @@ jobs:
         run: |
           available_targets=$(ls builder-support/dockerfiles/Dockerfile.target.* )
           for i in $(echo "${{ inputs.os }}"); do
-            if [[ echo $available_targets | grep -qq $i ]]; then
+            if echo $available_targets | grep -qq $i; then
               targets+=($i)
             else
               if [[ "${{ inputs.ref }}" == "master" ]]; then
-                echo "::failure title=Targer dockerfile not found for ${i}::OS ${i} not available as target in ${{ inputs.ref }}" && exit 1
+                echo "::error title=Targer dockerfile not found for ${i}::OS ${i} not available as target in ${{ inputs.ref }}" && exit 1
               else
                 echo "::warning title=Packages will not be generated for ${i}::OS ${i} not available as target in ${{ inputs.ref }}"
               fi
             fi
           done
           echo "oslist=$(jo -a ${targets[*]})" >> "$GITHUB_OUTPUT"
+          echo "oslist=$(jo -a ${targets[*]})"
       - id: get-runnerlist
         run: echo "runnerlist=$(jo -a ubuntu-24.04 ${{ vars.ARM64_USE_UBICLOUD == '1' && 'ubicloud-standard-2-arm' || '' }})" >> "$GITHUB_OUTPUT"
       - id: get-archlist
@@ -188,6 +189,7 @@ jobs:
           done
           sort -o /tmp/os-inputs.txt /tmp/os-inputs.txt
           echo "\"srchashes\"" | tee -a /tmp/os-inputs.txt
+          cat /tmp/os-inputs.txt && echo && cat /tmp/build-outputs.txt
       - name: Fail if there is a hash missing
         run: if ! diff -q /tmp/build-outputs.txt /tmp/os-inputs.txt; then exit 1; fi
 
