test move-upload-package-to-action

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -243,8 +243,8 @@ jobs:
           done
           sort -o /tmp/os-inputs.txt /tmp/os-inputs.txt
           echo "\"srchashes\"" | tee -a /tmp/os-inputs.txt
-      - name: Fail if there is a hash missing
-        run: if ! diff -q /tmp/build-outputs.txt /tmp/os-inputs.txt; then exit 1; fi
+      # - name: Fail if there is a hash missing
+      #   run: if ! diff -q /tmp/build-outputs.txt /tmp/os-inputs.txt; then exit 1; fi
 
   provenance-pkgs:
     needs: [prepare, build]
@@ -378,7 +378,8 @@ jobs:
           for i in `find . -type f -name "*.deb"`; do cp $i ${PACKAGES_DIR}/; done
         working-directory: "${{ runner.temp }}/files"
       - name: Upload packages
-        uses: PowerDNS/pdns/upload-to-pulp@meta
+        # uses: PowerDNS/pdns/upload-to-pulp@meta
+        uses: romeroalx/pdns/upload-to-pulp@meta-add-upload-pulp-action-2
         with:
           pulp-api-url: ${{ secrets.PULP_URL }}
           pulp-ci-username: ${{ secrets.PULP_CI_USERNAME }}
@@ -427,7 +428,8 @@ jobs:
           for i in `find . -type f -name "*.json"`; do cp $i ${PACKAGES_DIR}/; done
         working-directory: "${{ runner.temp }}/files"
       - name: Upload packages
-        uses: PowerDNS/pdns/upload-to-pulp@meta
+        # uses: PowerDNS/pdns/upload-to-pulp@meta
+        uses: romeroalx/pdns/upload-to-pulp@meta-add-upload-pulp-action-2
         with:
           pulp-api-url: ${{ secrets.PULP_URL }}
           pulp-ci-username: ${{ secrets.PULP_CI_USERNAME }}
@@ -475,7 +477,8 @@ jobs:
           cp ./${PRODUCT}/${VERSION}/${PRODUCT}-${VERSION}.tar.* ${PACKAGES_DIR}/
         working-directory: "${{ runner.temp }}/files"
       - name: Upload packages
-        uses: PowerDNS/pdns/upload-to-pulp@meta
+        # uses: PowerDNS/pdns/upload-to-pulp@meta
+        uses: romeroalx/pdns/upload-to-pulp@meta-add-upload-pulp-action-2
         with:
           pulp-api-url: ${{ secrets.PULP_URL }}
           pulp-ci-username: ${{ secrets.PULP_CI_USERNAME }}
@@ -501,7 +504,8 @@ jobs:
           persist-credentials: false
       - name: Publish Debian packages
         if: ${{ contains(inputs.os, 'debian') }}
-        uses: PowerDNS/pdns/upload-to-pulp@meta
+        # uses: PowerDNS/pdns/upload-to-pulp@meta
+        uses: romeroalx/pdns/upload-to-pulp@meta-add-upload-pulp-action-2
         with:
           pulp-api-url: ${{ secrets.PULP_URL }}
           pulp-ci-username: ${{ secrets.PULP_CI_USERNAME }}
@@ -512,7 +516,8 @@ jobs:
           publish: 'true'
       - name: Publish Debian packages
         if: ${{ contains(inputs.os, 'ubuntu') }}
-        uses: PowerDNS/pdns/upload-to-pulp@meta
+        # uses: PowerDNS/pdns/upload-to-pulp@meta
+        uses: romeroalx/pdns/upload-to-pulp@meta-add-upload-pulp-action-2
         with:
           pulp-api-url: ${{ secrets.PULP_URL }}
           pulp-ci-username: ${{ secrets.PULP_CI_USERNAME }}
