automated check failure

diff --git a/.github/workflows/test-odbc.yml b/.github/workflows/test-odbc.yml
--- a/.github/workflows/test-odbc.yml
+++ b/.github/workflows/test-odbc.yml
@@ -140,7 +140,7 @@ jobs:
       - name: Install jq
         run: "sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq -y jq"
       - name: output job context
-        run: "echo ${{ toJSON(needs) }}"
+        run: 'for i in `echo ${{ toJSON(needs) }}" | jq -n "inputs[].result"`; do if [[ $i == "\"failure\"" ]]; then exit 1; fi; done;'
       # - name: Get full list of jobs for this workflow
       #   run: yq e '.jobs | keys' .github/workflows/build-and-test-all.yml | grep -v '^- collect' | sort | tee /tmp/workflow-jobs-list.yml
       # - name: Get list of jobs the collect job depends on
